#ifndef LTNT_ERRORVALS_H_INCLUDED
#define LTNT_ERRORVALS_H_INCLUDED

typedef enum {
	ERR_OK=0,
	ERR_CONFIG=1,
	ERR_LATE_NOT_FOUND=2,
	ERR_IPERF_NOT_FOUND=20,
	ERR_WRONG_DATE=3,
	ERR_OPTIONS=4,
	ERR_UDP_SOCKET=5,
	ERR_TCP_SOCKET=6,
	ERR_TCP_SOCKET_CANNOT_LISTEN=7,
	ERR_DISC_SEND=8,
	ERR_TCP_SEND=9,
	ERR_TCP_RECV=10,
	ERR_SLAVE_UNRESPONSIVE=11,
	ERR_MASTER_UNRESPONSIVE=12,
	ERR_MALLOC=13,
	ERR_CONFIG_PARSE=14,
	ERR_MKDIR_LOGS_DIR=15,
	ERR_SET_TCP_FIN_TIMEOUT=16
} errorvals_t;

#endif