#!/bin/sh /etc/rc.common
 
USE_PROCD=1
 
START=99
STOP=01
 
CONFIGURATION=LTNT_test_manager_slave
 
start_service() {
    # Reading configuration parameters (i.e. control/PTP traffic interface)
    config_load "${CONFIGURATION}"
    local name
    local every
 
    config_get testif LTNT_test_manager_slave testif
 
    procd_open_instance
 
    # pass config to script on start
    procd_set_param command /bin/bash -c "cd /root/LTNT && ./LTNT_test_manager --slave -S $testif"
    procd_set_param file /etc/config/LTNT_test_manager_slave
    procd_set_param stdout 1
    procd_set_param stderr 1
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-60} ${respawn_retry:-0}
    procd_close_instance
}